import * as React from 'react';
import * as ReactDOMClient from 'react-dom/client';
import * as jsxRuntime from 'react/jsx-runtime';
import Dialog from '@jetbrains/ring-ui-built/components/dialog/dialog';
import LoaderInline from '@jetbrains/ring-ui-built/components/loader-inline/loader-inline';
import DatePicker from '@jetbrains/ring-ui-built/components/date-picker/date-picker';
import Checkbox from '@jetbrains/ring-ui-built/components/checkbox/checkbox';
import Radio from '@jetbrains/ring-ui-built/components/radio/radio';
import Tabs from '@jetbrains/ring-ui-built/components/tabs/dumb-tabs';
import Tab from '@jetbrains/ring-ui-built/components/tabs/tab';
import Table from '@jetbrains/ring-ui-built/components/table/table';
import Selection from '@jetbrains/ring-ui-built/components/table/selection';
import { enUS } from 'date-fns/locale/en-US';
import { ru } from 'date-fns/locale/ru';
import { fr } from 'date-fns/locale/fr';
import { de } from 'date-fns/locale/de';
import { zhCN } from 'date-fns/locale/zh-CN';
import { it } from 'date-fns/locale/it';
import { pl } from 'date-fns/locale/pl';
import { tr } from 'date-fns/locale/tr';
import { ja } from 'date-fns/locale/ja';
import { ko } from 'date-fns/locale/ko';
import { cs } from 'date-fns/locale/cs';
import { nl } from 'date-fns/locale/nl';
import { pt } from 'date-fns/locale/pt';
import { hu } from 'date-fns/locale/hu';
import { es } from 'date-fns/locale/es';
const DateFnsLocales = { en: enUS, ru, fr, de, 'zh-CN': zhCN, it, pl, tr, ja, ko, cs, nl, pt, hu, es };
globalThis.SSP_VENDORED = { React, ReactDOMClient, jsxRuntime, Dialog, LoaderInline, DatePicker, Checkbox, Radio, Tabs, Tab, Table, TableSelection: Selection, DateFnsLocales };
